version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - run: node --version

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-deploy:
    jobs:
      - test
